### ISSUE TITLE
Discuss whether there's still a need

### ISSUE THREAD

**Issue by yurrriq** [lfe-rebar3/clean#1]
As of lfe-rebar3/compile#12, `rebar3 lfe compile` now puts `.beam` files in the correct directory, so that part of the `clean` task is now obsolete.

As for the [other `files` and `dirs`](https://github.com/lfe-rebar3/clean/blob/0.2.0/src/lfe-clean.lfe#L11-L12) it deletes, it seems to me these are not at all LFE-specific (so maybe this isn't the best place) and that deleting them via a plugin is perhaps imprudent.

OTOH, I find myself `rm -rf`ing those guys occasionally, so a plugin like this might come in handy.

**Comment by oubiwann** [comment]
Definitely a need for this, and that has been done in https://github.com/lfe-rebar3/rebar3_lfe
